@startuml CreateCampground

header CampgroundBookingAPI Campground Sequence Diagram
footer Page %page% of %lastpage%
title "Create Campground (POST)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<middleware>>\n:protect" as protectMiddleware
participant "<<middleware>>\n:authorize" as authorizeMiddleware
participant "<<router>>\n:campgrounds" as routerCampgrounds
participant "<<controllers>>\n:campgrounds" as controllersCampgrounds
participant "<<model>>\n:Campground" as modelCampground
database "<<MongoDB>>\n:campgrounds" as CampgroundsDatabase

client->server ++:req.post('/api/v1/campgrounds')
server->protectMiddleware ++:protect (Verify JWT)
protectMiddleware --> server --:next (user attached)
server->authorizeMiddleware ++:authorize('admin')
alt user.role == 'admin'
  authorizeMiddleware --> server --:next
  server->routerCampgrounds ++:app.use('/api/v1/campgrounds',campgrounds)
  routerCampgrounds -> controllersCampgrounds ++:createCampground()
  controllersCampgrounds->modelCampground ++:create(req.body)
  modelCampground->CampgroundsDatabase ++: CampgroundSchema
  CampgroundsDatabase --> modelCampground --: campground
  controllersCampgrounds <-- modelCampground --:campground
  controllersCampgrounds->client --:response (campground)
else user.role != 'admin'
  authorizeMiddleware --> client --:response (error - not authorized)
end

@enduml
