@startuml DeleteCampground

header CampgroundBookingAPI Campground Sequence Diagram
footer Page %page% of %lastpage%
title "Delete Campground (DELETE)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<middleware>>\n:protect" as protectMiddleware
participant "<<middleware>>\n:authorize" as authorizeMiddleware
participant "<<router>>\n:campgrounds" as routerCampgrounds
participant "<<controllers>>\n:campgrounds" as controllersCampgrounds
participant "<<model>>\n:Campground" as modelCampground
participant "<<model>>\n:Booking" as modelBooking
database "<<MongoDB>>\n:campgrounds" as CampgroundsDatabase
database "<<MongoDB>>\n:bookings" as BookingsDatabase

client->server ++:req.delete('/api/v1/campgrounds/:id')
server->protectMiddleware ++:protect (Verify JWT)
protectMiddleware --> server --:next (user attached)
server->authorizeMiddleware ++:authorize('admin')
alt user.role == 'admin'
  authorizeMiddleware --> server --:next
  server->routerCampgrounds ++:app.use('/api/v1/campgrounds',campgrounds)
  routerCampgrounds -> controllersCampgrounds ++:deleteCampground()
  controllersCampgrounds->modelCampground ++:findById(id)
  modelCampground->CampgroundsDatabase ++: query by id
  CampgroundsDatabase --> modelCampground --: campground
  controllersCampgrounds <-- modelCampground --:campground
  alt campground exists
    controllersCampgrounds->modelBooking ++:deleteMany({campground: id})
    modelBooking->BookingsDatabase ++: delete all related bookings
    BookingsDatabase --> modelBooking --: deleted
    controllersCampgrounds <-- modelBooking --:success
    controllersCampgrounds->modelCampground ++:deleteOne({_id: id})
    modelCampground->CampgroundsDatabase ++: delete campground
    CampgroundsDatabase --> modelCampground --: deleted
    controllersCampgrounds <-- modelCampground --:success
    controllersCampgrounds->client --:response (success)
  else campground not exists
    controllersCampgrounds->client --:response (error - not found)
  end
else user.role != 'admin'
  authorizeMiddleware --> client --:response (error - not authorized)
end

@enduml
