@startuml UpdateCampground

header CampgroundBookingAPI Campground Sequence Diagram
footer Page %page% of %lastpage%
title "Update Campground (PUT)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<middleware>>\n:protect" as protectMiddleware
participant "<<middleware>>\n:authorize" as authorizeMiddleware
participant "<<router>>\n:campgrounds" as routerCampgrounds
participant "<<controllers>>\n:campgrounds" as controllersCampgrounds
participant "<<model>>\n:Campground" as modelCampground
database "<<MongoDB>>\n:campgrounds" as CampgroundsDatabase

client->server ++:req.put('/api/v1/campgrounds/:id')
server->protectMiddleware ++:protect (Verify JWT)
protectMiddleware --> server --:next (user attached)
server->authorizeMiddleware ++:authorize('admin')
alt user.role == 'admin'
  authorizeMiddleware --> server --:next
  server->routerCampgrounds ++:app.use('/api/v1/campgrounds',campgrounds)
  routerCampgrounds -> controllersCampgrounds ++:updateCampground()
  controllersCampgrounds->modelCampground ++:findByIdAndUpdate(id, req.body)
  modelCampground->CampgroundsDatabase ++: update by id
  CampgroundsDatabase --> modelCampground --: updatedCampground
  controllersCampgrounds <-- modelCampground --:updatedCampground
  alt campground exists
    controllersCampgrounds->client --:response (updatedCampground)
  else campground not exists
    controllersCampgrounds->client --:response (error - not found)
  end
else user.role != 'admin'
  authorizeMiddleware --> client --:response (error - not authorized)
end

@enduml
